language: node_js

env:
  - DB=postgresql://postgres@localhost:5432/waiter_availability_tests

node_js:
  - "8.9.4"

before_script:

  - psql -c 'create database waiter_availability_tests;' -U postgres
  - psql -U postgres -d waiter_availability_tests -a -f waiter-availabilty-script.sql

addons:
  apt:
  packages:
  - postgresql-server-dev-9.2
